name: News‑Crawl‑Job

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Run fetch script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python scripts/fetch_and_extract.py

      - name: Commit & push results
        run: |
          git config --global user.name "mj65-cmd"
          git config --global user.email "mj65-cmd@users.noreply.github.com"
          git add output/articles/*
          git diff --quiet && echo "No new files" || (git commit -m "auto update news" && git push)
